# Generated by Django 5.2.4 on 2025-08-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_created_at_review_stars_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriprion',
            new_name='description',
        ),
    ]
